language: node_js
node_js:
- '8'
env:
  secure: CcJkeuTxJp9uq6X2Yml1SvkXyb3piS7h3aBO4hJonlLhArKjT6XlWvhoehxlVPlId8vVqeWGBJhSblljD42s0cpD2eoOMgAYjLswv6N805bzizkav4dieHpT+UZVJDWHfSiTfhz0G3ZVzVxeLu+IvIdUOQnRiv89xVbWTmZmDmHc7EZ0ebHdW4UqKZCKNRzhLwbj9gNULL0yI7msirghKbYiEY3na1gnRY9cfLTc0uHjLr6lljZZ2EoED9hZqDnCYdJacf8t6n7jWEJdib4MZblQLng1pf5Xew2F52oyewWEwBZemblUp/RCtxUlHQI8TGPMe67vcrkj5RmakVyTVDi+H4btD9wTvppJlgWaDlYVZnLYvxTdugAG9mhR0JVWRTP/jmJxgDg6aIrg83KSoMlegmyerry+W18QtbjLsANHOB3XI5Mim0mC+3BZ0XgaEQcIOpZa+5oiw68zOLhWoBh02GuGZY7IvaCBnICagbyDupGeMg3ktWkf3K38wdCDOis0Kc0mFjwClo60eGxXd27SI+LijXoEP8c3/mtnIAWBBq0zjb20OGi9GosHi0KWp+K6ZXEZxdwTsNAoBlAzK/FaylBnUeL3j9jQIWUemKbY6iTKjYL51/XxWud1vGnIabZ6ZKHJ6OATM65JaajSBx0Pg8aj5tCxpDG7geZlq2A=
deploy:
  skip_cleanup: true
  provider: npm
  email: zzswang@south.farm
  api_key:
    secure: c1XMhEq7snBRQVhzf+xb80dctf3cwalOAKdcZLk/uhI8wgtbAcaxWI+JdfwFUiF0i0UJ+45Nc/wgHEVcgJrYpZmslt6QoMJZCQ1wPj+eAGwgeIMFd1QywIpJfFF16Rjz+LM5rS/YsgT0o2XwWQcrXhJ8NBERuffLhX30k09GZHEoK94XEkSvaCCf+rk7v1OK8w64Igg60SKUHh7r8CLKKIaYUHJfzWE7CE5Srjz47sFW0ovodID0+4Vr56Zpc7g6/19OOV7VdZRy4njGtu3Es3HotfIGzVHUfr/iiwBzcupmAC4KndkRLqQVpZd9L38vkTmc/pmV0CrXl62Msecu36/+vxQIR7Gtc+8r65XG/oIW+DAiiRFrlYzUf58lD3ahlraPg4FuoYT9d7eAaWTWTeCNj7EIcjfz9jFxH+AEmmDCijUXhewA3GNv+iqZdvAlLyVtadjhHJK/Gi+fkMgKb+R7XqW0b5ZkAYGcmxYLA/OW9S/sfnSQW3hNWEf7M4+MUuecYVha7R1FEwgtSckdFEffR2nlEvdsRLFi56ctI1z+hNJmnOBnNwlZ0Cf9PpCwdtijLahi1HyDbDjCgCfS34qSQsv1UkU6pjiAkCj0UIdFtQf99WURtFvIyG0EeiZqJynHDUv+dcRmf6aO1b6t6EP8wu7diH0r41IO/EqaqFI=
  on:
    tags: true
after_deploy:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG
  ; fi`
- if ([ ! -z "$TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$SKIP_BUILD"
  != "true" ]); then echo "Slack notice on tag ${TAG}"; curl -X POST -H 'Content-type:application/json'
  --data '{"text":"<https://github.com/south-farm/es-dev-tools|es-dev-tools> 发布 '$TAG' 版本。\n<https://github.com/south-farm/es-dev-tools/blob/master/CHANGELOG.md|看看有什么新货色>"}' $SLACK_URL;
  fi
